name: Terminal Screen Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install opam -y
          opam init --auto-setup
          opam switch create 5.2.0
          opam install dune -y
          opam install . --deps-only -y
      - name: Set up Opam Environment
        run: eval $(opam env)
      - name: Build Project
        run: dune build
      - name: Run Tests
        run: dune runtest
      - name: Format Check
        run: dune build @fmt --auto-promote
      - name: Lint Code
        run: opam exec -- ocamlformat --check --enable-outside-detected-project **/*.ml
          **/*.mli
      - name: Verify Installation
        run: opam exec -- dune install
