name: Terminal Screen Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: "5.2.0"
          opam-depext: true

      - name: Install Dependencies
        run: |
          opam install . --deps-only -y
          eval $(opam env)

      - name: Build Project
        run: opam exec -- dune build

      - name: Run Tests
        run: opam exec -- dune runtest

      - name: Format Check
        run: opam exec -- dune build @fmt --auto-promote

      - name: Lint Code
        run: opam exec -- ocamlformat --check --enable-outside-detected-project **/*.ml **/*.mli

      - name: Verify Installation
        run: opam exec -- dune install
